name: Kira Neural Sync

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Core
        run: pip install metaapi-cloud-sdk pandas
      - name: Run Kira
        env:
          MT5_TOKEN: ${{ secrets.MT5_TOKEN }}
          MT5_ACCOUNT_ID: ${{ secrets.MT5_ACCOUNT_ID }}
        run: python quantum_analysis.py
      - name: Push Data
        run: |
          git config --global user.name "Kira-Bot"
          git config --global user.email "kira@neural.hub"
          git add "Kira mt4.html"
          git commit -m "Update Neural Dashboard" || exit 0
          git push
